FROM scratch
MAINTAINER \
[Adam Miller <maxamillion@fedoraproject.org>] \
[Patrick Uiterwijk <patrick@puiterwijk.org>]
ENV DISTTAG=f29container FGC=f29 FBR=f29
ADD fedora-29-aarch64-20181015.tar.xz /
