FROM scratch
MAINTAINER \
[Adam Miller <maxamillion@fedoraproject.org>] \
[Patrick Uiterwijk <patrick@puiterwijk.org>]
ENV DISTTAG=f28container FGC=f28 FBR=f28
ADD fedora-28-aarch64-20181101.tar.xz /
